Python 3.8+ port
exaskye/FlexVer pull request #22
Opened 2023-09-22 13:07 UTC by ENDERZOMBI102

Implement FlexVer in Python via a `FlexVer` class which implements total ordering and a `compare(str, str): int` function which is like the Java `FlexVerComparator.compare()` implementation.

This was tested on Python 3.8 up to 3.11.

If this is accepted, We will publish it to [PyPi](https://PyPi.org) under the `flexver` name.

- [x] I own the full rights to my contribution, and agree to release it under the terms of the Creative Commons Zero Public Domain Dedication

2023-10-09 08:22 UTC, unascribed requested changes
Sorry, I missed this somehow.

Code looks OK at a glance — I'm not a Python dev, so, not really qualified to comment on that, but it's a much shorter impl than #11.

The workflow needs to be fixed for this to be mergeable. Thanks for working on it!

2023-10-09 08:22 UTC, unascribed commented on .github/workflows/test-python.yml
> +    - run: poetry build -n    # build
This does not run in Actions due to the executable not being in the PATH.

2023-10-09 15:04 UTC, Infinidoge requested changes
First and foremost, sorry for never actually finishing #11, kept meaning to but just never got around to it.

With that said, this is a great implementation, and definitely a lot cleaner than mine!
The main nitpicks I have are style, namely:
- Extra spaces inside parenthesis/brackets (which is sometimes inconsistent, such as line 120)
- `camelCase` method names instead of `snake_case` method names

These don't affect how the code runs though, so it isn't necessary to change them.

There were also some `\t`s in doc strings, and a slight code change, which I made comments for.

Thanks for picking up my dropped ball, and looking forward to seeing this on PyPI!

2023-10-09 15:04 UTC, Infinidoge commented on python/flexver.py
> +		\t
Not sure what this `\t` is doing here

2023-10-09 15:04 UTC, Infinidoge commented on python/flexver.py
> +	\t
Another `\t`

2023-10-09 15:04 UTC, Infinidoge commented on python/test_flexver.py
> +			setattr( FlexVerTestCase, f'test_{index}', createTest( index, line ) )
No problem here, just stunned by how I never thought about doing something like this for dynamically generated test cases.

2023-10-09 15:04 UTC, Infinidoge commented on python/test_flexver.py
> +				line = line[: -1]
```suggestion
			line = line.rstrip('\n')
```

2023-10-09 15:39 UTC, ENDERZOMBI102 commented on python/flexver.py
> +		\t
those are for IDEs, we've come to understand that some show reStructuredText-formatted parameters anyway, but the `\t` stops it from happening

2023-10-09 15:49 UTC, ENDERZOMBI102 commented
for the spaces between parentheses, its for readability, they help us understand divide symbols and words, make things easier to parse.
although can remove if needed.

the c`camelCase` is just personal preference, will change the casing as we've also noticed that the PEP says to use `snake_case`

2023-10-09 16:03 UTC, Infinidoge commented on python/flexver.py
> +		\t
I do not understand IDEs sometimes. I just want my plain text left alone :(

Makes sense to have it then.

2023-10-09 19:36 UTC, ENDERZOMBI102 commented
moved to `snake_case` and fixed workflow/tests

2023-10-09 22:54 UTC, Infinidoge submitted a review, later dismissed
Small consistency nitpicks.
Can alternatively remove the spaces around `_VersionComponent`/other types.

2023-10-09 22:54 UTC, Infinidoge commented on python/flexver.py
> +_null: typing.Final[ _VersionComponent] = _NullVersionComponent()
```suggestion
_null: typing.Final[ _VersionComponent ] = _NullVersionComponent()
```

2023-10-09 22:54 UTC, Infinidoge commented on python/flexver.py
> +	bd: typing.List[ _VersionComponent] = _decompose(b)
```suggestion
	ad: typing.List[ _VersionComponent ] = _decompose(a)
	bd: typing.List[ _VersionComponent ] = _decompose(b)
```

2023-10-09 22:54 UTC, Infinidoge commented on python/flexver.py
> +def _get( li: typing.List[ _VersionComponent], i: int ) -> _VersionComponent:
```suggestion
def _get( li: typing.List[ _VersionComponent ], i: int ) -> _VersionComponent:
```

2023-10-10 00:16 UTC, unascribed approved these changes
Workflow now runs and the tests pass.

2023-10-10 00:20 UTC, merged

2023-10-10 00:20 UTC, unascribed commented
Thanks!

2023-10-10 10:26 UTC, ENDERZOMBI102 commented
published! as said, can be found under `flexver` on pypi: https://pypi.org/project/flexver